puts "Destroying database..."

Admin.destroy_all
Brewery.destroy_all
Review.destroy_all

puts "Database destroyed"

puts "Creating admin...👥"

Admin.create(name:"Charlie", username: "admin", password: "password")

puts "Admin created"

puts "Creating breweries...🍻"

b1= Brewery.create(name:"Brick & Feather", location: "Tuners Falls", url:"https://www.brickandfeatherbrewery.com/", strength:"Lager", charlies_choice:"Small Group of Reasonable People (4%)", rating:"6/10", amenities:"Small, summer patio, adjacent river paths", image_url:"https://www.google.com/search?q=brick+and+feather&client=firefox-b-1-d&sxsrf=ALiCzsZ_Mi39MF0M09d3PXpuPniF3-gnAQ:1671739374680&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjnxda8go78AhVei3IEHQhbAvEQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=6Ht7CNKrsvDyKM", vibe:"Hipster, quiet, friendly")
b2= Brewery.create(name:"Pioneer Valley", location: "Tuners Falls", url:"https://pioneervalleybrew.com/", strength:"Mix", charlies_choice:"Fogbuster Coffee Stout (6.5%)", rating:"7/10", amenities:"Large patio, fire pit, games, line dancing ", image_url:"https://www.google.com/search?q=pioneer+valley+brew&client=firefox-b-1-d&sxsrf=ALiCzsbqqxehRrIBWNF2XHtmy6Jnn7YM9A:1671737964182&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiQwIyc_Y38AhWAlGoFHVd1CZ8Q_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=SDngaVq92MQrKM", vibe:"Older crowd, hyperlocal, friendly but not overall welcoming")
b3= Brewery.create(name:"Four Phantoms", location: "Greenfield", url:"https://www.fourphantoms.net/", strength:"Seasonal/Dark", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=four+phantoms+brewery&client=firefox-b-1-d&sxsrf=ALiCzsY7-Pv74cHeUHN0bJxqCu4AbwxlMg:1671737318403&source=lnms&tbm=isch&sa=X&ved=2ahUKEwilq5Xo-o38AhXmmWoFHfAFDBkQ_AUoA3oECAEQBQ&biw=1536&bih=731&dpr=1.25#imgrc=bwWHKc6Ew8HkaM", vibe:"")
b4= Brewery.create(name:"People's Pint", location: "Greenfield", url:"https://thepeoplespint.com/", strength:"IPA", charlies_choice:"Wandering Woolly Bear (dark lager, 6.9%, dessert beer)", rating:"8/10", amenities:"Small, dark, quiet, AMAZING food", image_url:"https://www.google.com/search?q=people%27s+pint+brew&client=firefox-b-1-d&sxsrf=ALiCzsbpIK0vIAD1Sk-NsjSh09uh0KWrxA:1671737888654&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjbxor4_I38AhVal2oFHSh0AzMQ_AUoA3oECAEQBQ&biw=1536&bih=731&dpr=1.25#imgrc=zI_cdHBJS94qbM", vibe:"Down to earth, friendly, local crowd")
b5= Brewery.create(name:"Element Brew", location: "Miller's Falls", url:"http://www.elementbeer.com/", strength:"Dark Malt/Ale", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=element+brew&client=firefox-b-1-d&sxsrf=ALiCzsaMrdKBM6_cbPS4COi3UimmyZwIzQ:1671739401675&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjdkMbJgo78AhWJl3IEHS3HBfAQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=KDOaHk5FLCfRTM", vibe:"")
b6= Brewery.create(name:"Hitchcock Brew", location: "Bernardston", url:"https://www.hitchcockbrewing.com/", strength:"Ale/Sour/IPA", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=hitchcock+brewery&client=firefox-b-1-d&sxsrf=ALiCzsb_V9bmz6DgLhBDp3pWhumwi39HRg:1671737462190&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjptN2s-438AhUZlWoFHTlODs0Q_AUoA3oECAEQBQ&biw=1536&bih=731&dpr=1.25#imgrc=rkxBQQCGE0T9zM", vibe:"")
b7= Brewery.create(name:"Brewery @ 4 Star", location: "Northfield", url:"https://www.fourstarbeer.com/", strength:"Mix/Seasonal", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=brew+at+4+stars&client=firefox-b-1-d&sxsrf=ALiCzsa5JzFY_0DZ8RkNb3A_0RJfEivr_w:1671738618721&source=lnms&tbm=isch&sa=X&ved=2ahUKEwihr5rU_438AhUbl2oFHaZvAn8Q_AUoAXoECAEQAw&biw=1536&bih=731&dpr=1.25#imgrc=lGkfVOo3TRgtEM", vibe:"")
b8= Brewery.create(name:"Back Room Brew", location: "Northfield", url:"https://thebackroombrewingcompany.com/", strength:"Ale", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=back+room+brew+ma&tbm=isch&ved=2ahUKEwjjhorbgo78AhWWDd4AHTKvDCEQ2-cCegQIABAA&oq=back+room+brew+ma&gs_lcp=CgNpbWcQAzoJCAAQgAQQChAYUN0EWL4HYO0IaABwAHgAgAHEBIgBtQeSAQcwLjMuNS0xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=LrikY-O3Gpab-LYPst6yiAI&bih=731&biw=1536&client=firefox-b-1-d#imgrc=PJ_UEfKB-47ggM", vibe:"")
b9= Brewery.create(name:"Floodwater Brew", location: "Shelburne Falls", url:"http://www.floodwaterbrewing.com/index.html", strength:"Mix", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=floodwater+brewery&client=firefox-b-1-d&sxsrf=ALiCzsargoA9ROsZDK-r6XZlBZzXnJYFDg:1671737191178&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjNhMCr-o38AhUclWoFHQ1HB1EQ_AUoAnoECAIQBA&biw=1536&bih=731&dpr=1.25#imgrc=PpnTZS_NWi-ZHM", vibe:"")
b10= Brewery.create(name:"Stoneman Brew", location: "Colrain", url:"https://www.facebook.com/stonemanbrewery/", strength:"Not Listed", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=stoneman+brewery&client=firefox-b-1-d&sxsrf=ALiCzsbhJokMRnrPaz-LP9R2lE6A8VaN7Q:1671738561509&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjuufa4_438AhWElmoFHY8uDHoQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=wXJX96qsRzt6EM", vibe:"")
b11= Brewery.create(name:"Treehouse Brew", location: "Deerfield", url:"https://treehousebrew.com/", strength:"Mix", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=tree+house+brew&client=firefox-b-1-d&sxsrf=ALiCzsb56QLA2ZUUfzVN1EWcFyp_Xv6Kog:1671738726472&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiw8cqHgI78AhWSmGoFHSoEArQQ_AUoA3oECAEQBQ&biw=1536&bih=731&dpr=1.25#imgrc=oyJXjSI_1N8DTM", vibe:"")
b12= Brewery.create(name:"Birkshire Brew", location: "S. Deerfield", url:"https://www.berkshire-brewing.com/", strength:"Ale/IPA", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=berkshire+brew&client=firefox-b-1-d&sxsrf=ALiCzsbRwZFvBAsecQAzU6Q-xcgUmLh78Q:1671739473949&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiSqIHsgo78AhWXi3IEHVtXBOoQ_AUoBHoECAEQBg&biw=1536&bih=731&dpr=1.25#imgrc=pPxK-Jh7oSPWXM", vibe:"")
b13= Brewery.create(name:"Powder Hollow", location: "S. Deerfield", url:"http://www.powderhollowbrewery.com/", strength:"Ale/IPA", charlies_choice:"Not memorable", rating:"3/10", amenities:"Two locations, attached to a Yankee Candle so the smell knocked me on my ass", image_url:"https://www.google.com/search?q=powder+hollow+brew&client=firefox-b-1-d&sxsrf=ALiCzsYvydEDN6_ynekGyRPQLmnG9faFHg:1671738009176&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiS38ax_Y38AhUgk2oFHWCKD8EQ_AUoA3oECAEQBQ&biw=1536&bih=731&dpr=1.25#imgrc=wBM6AQoEPNvNzM", vibe:"Corporate, quiet, kid friendly, sticky??")
b14= Brewery.create(name:"Brewmasters", location: "Williamsburg", url:"https://www.opentable.com/r/the-brewmasters-tavern-williamsburg", strength:"IPA/Sour/Seasonal", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=brewmasters+williamsburg+ma&tbm=isch&ved=2ahUKEwjcwIGAg478AhWHxckDHaLmDQsQ2-cCegQIABAA&oq=brewmasters+williamsburg+ma&gs_lcp=CgNpbWcQAzIHCAAQgAQQGDoECCMQJzoFCAAQgAQ6CQgAEIAEEAoQGDoECAAQHjoGCAAQBRAeUPgEWNIgYNshaABwAHgBgAGbAogB5hGSAQYzLjE0LjGYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=e7ikY5yXNoeLp84Pos23WA&bih=731&biw=1536&client=firefox-b-1-d#imgrc=tqVzaLcKWfwqOM&imgdii=tvysah0VLx4pnM", vibe:"")
b15= Brewery.create(name:"Amherst Brew", location: "Amherst", url:"https://www.amherstbrewing.com/brewery", strength:"IPA/Light", charlies_choice:"Orange Dreamsicle IPA (not good, but that's on me)", rating:"6/10", amenities:"Attached to Hanger Pub & Grill, arcade room, trivia nights", image_url:"https://www.google.com/search?q=amherst+brew&client=firefox-b-1-d&sxsrf=ALiCzsZdVE0SPXzTP6RpWIQKXMEkikgj2g:1671739598865&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjl1smng478AhUqrHIEHeh9A_QQ_AUoAnoECAIQBA&biw=1536&bih=731&dpr=1.25#imgrc=enLDfOTi2IKEbM", vibe:"Sports bar, older crowd, hyperlocal, think BJs")
b16= Brewery.create(name:"Northhampton Brew", location: "Northhampton", url:"https://northamptonbrewery.com/", strength:"Stout/Porter", charlies_choice:"S'more Porter (6.7%)", rating:"5/10", amenities:"Good location, rooftop bar, dark, lot's of private seating, overpriced food", image_url:"https://www.google.com/search?q=northampton+brewery&client=firefox-b-1-d&sxsrf=ALiCzsZQHzjqd9s1CCXSpTjMGRtvuV9taw:1671737788906&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjwr7nI_I38AhXNmWoFHd4CCp4Q_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=wOOqiGftsnO-9M", vibe:"Slightly nicer than a Chili's, but less interesting")
b17= Brewery.create(name:"Building 8 Brew", location: "Northhampton", url:"https://www.facebook.com/profile.php?id=100057152392802", strength:"No beer list", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=building+8+brewery&client=firefox-b-1-d&sxsrf=ALiCzsZU9UQYAAJBe_OhB9pIbIkC91VcTQ:1671739667254&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiar5fIg478AhVEmHIEHUPnDvAQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=4kHk3yBbxIXjQM", vibe:"")
b18= Brewery.create(name:"Progression Brew", location: "Northhampton", url:"https://progressionbrewing.com/", strength:"IPA", charlies_choice:"Adults are Talking (NEIPA), Omen Imperial Stout", rating:"7/10", amenities:"Table top games, live music every Saturday, have heard bad things about the food", image_url:"https://www.google.com/search?q=progression+brewery&client=firefox-b-1-d&sxsrf=ALiCzsaU7UPUYXW4xCFbHTgtFxSmHPStwg:1671738053931&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjPpvLG_Y38AhUSnWoFHRHRDUcQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=sz7385ZKQGyT6M", vibe:"Very queer (ya boi got a bartender's digits), loud, expensive (NOHO), mixed crowd")
b19= Brewery.create(name:"Fort Hill Brew", location: "Easthampton", url:"http://www.forthillbrewery.com/", strength:"German", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=fort+hill+brewing&client=firefox-b-1-d&sxsrf=ALiCzsYMDNsq8y5_YhPjqu22yE-ImDI7pQ:1671737236513&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjng4_B-o38AhXKm2oFHYZkDjwQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=YVmffry7L7ZsKM", vibe:"")
b20= Brewery.create(name:"New City Brew", location: "Easthampton", url:"https://www.newcitybrewery.com/", strength:"Mule/IPA", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=new+city+brewery&client=firefox-b-1-d&sxsrf=ALiCzsbvRd2nKKlCnHAI5eGe0LSSa-rvXg:1671737749658&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiOhee1_I38AhVdkWoFHSnEAPcQ_AUoA3oECAEQBQ&biw=1536&bih=731&dpr=1.25#imgrc=pIH-KmDv9AHPRM", vibe:"")
b21= Brewery.create(name:"Abandoned Building Brew", location: "Easthampton", url:"https://www.abandonedbuildingbrewery.com/", strength:"Mix", charlies_choice:"Dirty Girl IPA/Cool Beans (coffee stout)", rating:"8/10", amenities:"Patio, trivia nights, dog friendly, dark, confusing to naviagate (not mad about it)", image_url:"https://www.google.com/search?q=abandoned+building+brew&client=firefox-b-1-d&sxsrf=ALiCzsaG8D4bQIgBxF6PJIWcaDl8dpw4Hg:1671739701796&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi9hdTYg478AhU2oXIEHZ3HBfIQ_AUoAXoECAEQAw&biw=1536&bih=731&dpr=1.25#imgrc=X5lhhoJ8759S_M", vibe:"...abandoned.")
b22= Brewery.create(name:"Drunkin Rabbit Brew", location: "S. Hadley", url:"https://www.rabbit.beer/", strength:"Sour/IPA", charlies_choice:"Mango Milkshake Machine IPA (Sounds gross but so good)", rating:"8/10", amenities:"Summer patio, trivia and bingo nights, table top games, fun flavors (but mostly sours)", image_url:"https://www.google.com/search?q=drunken+rabbit+brew&client=firefox-b-1-d&sxsrf=ALiCzsb0cj40QxoRI6Ichs28nRZky6up0Q:1671739735228&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjOxszog478AhWXmGoFHYFYCbMQ_AUoA3oECAEQBQ&biw=1536&bih=731&dpr=1.25#imgrc=NXa1vJXDBv8S9M", vibe:"Down to earth, experimental, quiet.")
b23= Brewery.create(name:"Holyoke Craft Beer", location: "Holyoke", url:"https://www.facebook.com/HolyokeCraftBeer/", strength:"Not Listed", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=holyoke+craft+beer&client=firefox-b-1-d&sxsrf=ALiCzsZg8vtMxJc_sXKyKyyMbgP-sibGTQ:1671737506518&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjQ8e7B-438AhWclmoFHT1ACOYQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=sFWX86tE3J9RfM", vibe:"")
b24= Brewery.create(name:"Leadfoot Brew", location: "Holyoke", url:"https://www.leadfootbrewing.com/", strength:"Mix", charlies_choice:"", rating:"", amenities:"Patio", image_url:"https://www.google.com/search?q=leadfoot+brewing&client=firefox-b-1-d&sxsrf=ALiCzsawvSam06TvfEnvi6scOvIZqbpPUw:1671737699867&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjn-oee_I38AhUvk2oFHb4pBKUQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=UcF2xYwe8V9bRM", vibe:"")
b25= Brewery.create(name:"Vanished Valley Brew", location: "Ludlow", url:"https://vanishedvalley.com/", strength:"Mix (large selection)", charlies_choice:"Into The Shadows IPA (11% - proceed with caution)", rating:"7/10", amenities:"HUGE patio - great food.", image_url:"https://www.google.com/search?q=vanished+valley+brew&client=firefox-b-1-d&sxsrf=ALiCzsa5zIxPFwtJ2NJ4BsbmKkobPSpQFw:1671738840645&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjIr4O-gI78AhWzmmoFHeNxCtwQ_AUoBHoECAEQBg&biw=1536&bih=731&dpr=1.25#imgrc=BCTp9l_MzxR8CM", vibe:"Older crowd, suburban dad/live laugh love/conservative uncle vibe.")
b26= Brewery.create(name:"Iron Duke Brew", location: "Ludlow", url:"https://irondukebrewing.com/", strength:"Mix/IPA", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=iron+duke+brewery&client=firefox-b-1-d&sxsrf=ALiCzsbMRck53RfgTXmfKPacgXZlhxMj4A:1671737567306&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiGjO3e-438AhXRnWoFHeT8AAIQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=DtPE1zuVmTVppM", vibe:"")
b27= Brewery.create(name:"Rustic Brewing Co.", location: "Indian Orchard", url:"https://www.rusticbrewco.com/", strength:"IPA/Stout", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=rustic+brewing+co&client=firefox-b-1-d&sxsrf=ALiCzsZq4g4qUmecO6r91OG5ETF9phc4xg:1671738102952&source=lnms&tbm=isch&sa=X&ved=2ahUKEwidv6Le_Y38AhWCl2oFHYfIDFEQ_AUoA3oECAEQBQ&biw=1536&bih=731&dpr=1.25#imgrc=ocbUEZJ6RLSiGM", vibe:"")
b28= Brewery.create(name:"Fieldcrest Brew", location: "Wilbraham", url:"http://fieldcrestbrewing.com/contact-us/", strength:"Ale/IPA", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=field+crest+brewery&client=firefox-b-1-d&sxsrf=ALiCzsYm9fXc7YTQEg83qmBwJZZojs5Yjg:1671736967318&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjQ3-DA-Y38AhXug2oFHUL9C2kQ_AUoA3oECAEQBQ&biw=1536&bih=731&dpr=1.25#imgrc=LinOoYaZEw50HM", vibe:"")
b29= Brewery.create(name:"White Lion Brew", location: "Springfield", url:"https://www.whitelionbrewing.com/", strength:"IPA/Sour", charlies_choice:"", rating:"", amenities:"Downtown/Bad parking, large selection.", image_url:"https://www.google.com/search?q=white+lion+brewery&client=firefox-b-1-d&sxsrf=ALiCzsY3rff56h1v1d3_IECZhqi1ANUOhg:1671739309077&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjiu7Kdgo78AhXchXIEHZRBA-gQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=GEnKudli83v56M", vibe:"")
b30= Brewery.create(name:"Two Weeks Notice Brew", location: "W. Springfield", url:"https://www.twoweeksnoticebrewing.com/", strength:"IPA", charlies_choice:"Resignation (6.8%)", rating:"10/10", amenities:"Large patio, great music, patio games, tacos.", image_url:"https://www.google.com/search?q=two+weeks+notice+brewery&client=firefox-b-1-d&sxsrf=ALiCzsawXSua_P0VGX7Q0BfQ-QLnCenHSQ:1671738791006&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj5462mgI78AhVrm2oFHcj8CJkQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=ju362kWo8uDCfM", vibe:"Anti-capitaliast, blue collar, punk, doesn't know what a taco is but they own it. LOVE.")
b31= Brewery.create(name:"Tin Bridge Brew Co.", location: "Westfield", url:"https://www.tinbridgebrewingco.com/", strength:"IPA/Ale", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=tin+bridge+brew&client=firefox-b-1-d&sxsrf=ALiCzsb-wn-kStwDtICIR5BWvseK4lBsLQ:1671738675851&source=lnms&tbm=isch&sa=X&ved=2ahUKEwivmrnv_438AhXwmmoFHcpsC2AQ_AUoA3oECAEQBQ&biw=1536&bih=731&dpr=1.25#imgrc=RwjRupGsm06dUM", vibe:"")
b32= Brewery.create(name:"Great Awakening Brew", location: "Westfield", url:"https://greatawakeningbrewing.com/", strength:"Sour/Ale", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=great+awakening+brewery&client=firefox-b-1-d&sxsrf=ALiCzsYrrbchItCbwVBk5prP3UrkLoFFwA:1671737364208&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjJ4YD--o38AhWXmGoFHYFYCbMQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=ymmUEY2_-roofM", vibe:"")
b33= Brewery.create(name:"Skyline Beer Co.", location: "Westfield", url:"https://skylinebeerco.com/", strength:"Mix", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=skyline+beer+co&client=firefox-b-1-d&sxsrf=ALiCzsaBc73PA_eIFZwiNytSztvhOvcIXg:1671738502903&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjQsf2c_438AhVXlGoFHaaOAAcQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=ZHJlTYsGTSLGGM", vibe:"")
b34= Brewery.create(name:"Kismet Brew", location: "Westfield", url:"https://kismetbrewing.com/", strength:"IPA/Sour", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=kismet+brewery&client=firefox-b-1-d&sxsrf=ALiCzsbb9OU1Ww5_5-4Fw2vx-NuV43VwEg:1671737602588&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiKyNbv-438AhUom2oFHed4BpoQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=dHtJs3M_6HCnhM", vibe:"")
b35= Brewery.create(name:"Brew Practicioners", location: "Longmeadow", url:"https://brewpractitioners.com/", strength:"Mix/Ale", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=brew+practitioners&client=firefox-b-1-d&sxsrf=ALiCzsYDRAe2juEbFr0tyJhhD08Zf4NZ3w:1671739764560&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiV78r2g478AhWtknIEHVV6Cu8Q_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=Y2EeuQ0YEN9hHM", vibe:"")
b36= Brewery.create(name:"Bright Ideas Brew", location: "North Adams", url:"https://www.brightideasbrewing.com/", strength:"IPA/Ale", charlies_choice:"", rating:"", amenities:"Inside Mass MoCa", image_url:"https://www.google.com/search?q=bright+ideas+brew&client=firefox-b-1-d&sxsrf=ALiCzsYtcoVGINO2TlNqntLmrepqFD-2CQ:1671739795467&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjanamFhI78AhVbl2oFHZvOB6AQ_AUoAXoECAIQAw&biw=1536&bih=731&dpr=1.25#imgrc=eCKuLsO4jmua3M", vibe:"")
b37= Brewery.create(name:"Shire Breu-Hous", location: "Dalton", url:"https://www.shire.beer/#", strength:"Dark/Ale", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=shire+breu+haus&client=firefox-b-1-d&sxsrf=ALiCzsYc5eQ9e6EBXptBBp_IQZuG3BETuQ:1671738302131&source=lnms&tbm=isch&sa=X&ved=2ahUKEwipo5-9_o38AhWGkmoFHfO-BD0Q_AUoA3oECAEQBQ&biw=1536&bih=731&dpr=1.25#imgrc=c8Atnb7wstpTdM", vibe:"")
b38= Brewery.create(name:"Wandering Star Craft Brew", location: "Pittsfield", url:"https://www.facebook.com/profile.php?id=100028388906728", strength:"Mix", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=barrington+brew&client=firefox-b-1-d&sxsrf=ALiCzsZxoHx4DnoZ4pqWBkrbeSg6WRJWGQ:1671739825466&source=lnms&tbm=isch&sa=X&ved=2ahUKEwibr9CThI78AhXxhXIEHUkCC-oQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=EC24nTDbp44-5M", vibe:"")
b39= Brewery.create(name:"Barrington Brew", location: "Barrington", url:"https://www.barringtonbrewery.net/", strength:"Mix", charlies_choice:"", rating:"", amenities:"", image_url:"https://www.google.com/search?q=barrington+brew&client=firefox-b-1-d&sxsrf=ALiCzsZxoHx4DnoZ4pqWBkrbeSg6WRJWGQ:1671739825466&source=lnms&tbm=isch&sa=X&ved=2ahUKEwibr9CThI78AhXxhXIEHUkCC-oQ_AUoAnoECAEQBA&biw=1536&bih=731&dpr=1.25#imgrc=EC24nTDbp44-5M", vibe:"")
b40= Brewery.create(name:"Big Elm Brew", location: "Sheffield", url:"https://www.bigelmbeer.com/", strength:"IPA/Ale", charlies_choice:"", rating:"", amenities:"Very gluten free friendly", image_url:"https://utfb-images.untappd.com/logos/11f9fcbcb6c3780f432686a04a784537ce63cc38.jpg?auto=compress", vibe:"")

puts "Breweries seeded!"

puts "Creating reviews...🔖"

Review.create(name:"Jack", review:"I am a dog", brewery_id: b1, image_url: "https://dogsbestlife.com/wp-content/uploads/2022/09/Catahoula-Leopard-dog-scaled.jpeg")

puts "Reviews created"

